apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-a6a7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-a6a7"
  template:
    metadata:
      labels:
        app: "akscluster-a6a7"
    spec:
      containers:
        - name: "akscluster-a6a7"
          image: "akstestregistry2020.azurecr.io/akscluster"
          ports:
          - containerPort: 80